apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Infrastructure
  - ../../infrastructure/cert-manager/application.yaml
  - ../../infrastructure/ingress-nginx/application.yaml
  - ../../infrastructure/monitoring/application.yaml
  # Applications
  - ../../apps/overlays/dev
