apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/frontend.yaml
  - ../../base/backend.yaml

patches:
  - target:
      kind: Application
      name: frontend
    patch: |-
      - op: add
        path: /spec/source/helm/valueFiles/-
        value: ../../apps/overlays/staging/frontend-values.yaml
  - target:
      kind: Application
      name: backend
    patch: |-
      - op: add
        path: /spec/source/helm/valueFiles/-
        value: ../../apps/overlays/staging/backend-values.yaml
